# Testing the Code

In [1]:
#from Utils import get_features
import numpy as np

In [2]:
x = np.load('X_test_full.npy',allow_pickle=True)

In [3]:
len(x)

5371

In [3]:
vecs_1,vecs_2,vecs_3 = get_features(text='messi.txt',question='What disease was Messi diagnosed with?',num_rel_sentences=3)

In [4]:
list(vecs_1.keys())

[his growth hormone treatment,
 Messi,
 Barcelona's greatest-ever youth side,
 Baby Dream Team,
 an integral part]

In [7]:
list(vecs_1.values())[0]

array([0.60092825, 0.17240223, 1.        , 0.        , 3.        ,
       0.        , 4.        ])

In [5]:
vecs_1

defaultdict(None,
            {his growth hormone treatment: array([0.60092825, 0.17240223, 1.        , 0.        , 3.        ,
                    0.        , 4.        ]),
             Messi: array([-0.03365253,  0.28499755,  1.        ,  1.        ,  1.        ,
                     0.        ,  1.        ]),
             Barcelona's greatest-ever youth side: array([0.3216458 , 0.28499755, 1.        , 0.        , 4.        ,
                    0.        , 7.        ]),
             Baby Dream Team: array([0.25928894, 0.28499755, 1.        , 0.        , 3.        ,
                    0.        , 3.        ]),
             an integral part: array([0.28065234, 0.28499755, 1.        , 0.        , 1.        ,
                    0.        , 3.        ])})

# Using the Dataset

In [8]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import spacy

Getting the Data/Cleaning:

In [25]:
Answer_File = '../../Data/Question_Answer_Dataset_v1.2/S08/question_answer_pairs.txt'

In [26]:
with open(Answer_File,'r',encoding="ISO-8859-1") as f:
    Questions = f.read().split('\n')

In [27]:
Data = {key:[] for key in Questions[0].split('\t')}

In [28]:
keys = list(Data.keys())

In [29]:
for row in range(1,len(Questions)):
    data_point = Questions[row].split('\t')
    if len(data_point)>1:
        for i in range(len(data_point)):
            Data[keys[i]].append(data_point[i])

In [30]:
df = pd.DataFrame(Data)

ValueError: All arrays must be of the same length

In [31]:
df

ArticleTitle                                           Question  \
0    Alessandro_Volta                    Was Volta an Italian physicist?   
1    Alessandro_Volta                    Was Volta an Italian physicist?   
2    Alessandro_Volta         Is Volta buried in the city of Pittsburgh?   
3    Alessandro_Volta         Is Volta buried in the city of Pittsburgh?   
4    Alessandro_Volta  Did Volta have a passion for the study of elec...   
..                ...                                                ...   
820         Xylophone  What is the earliest historical reference in E...   
821         Xylophone    How are western-style xylophones characterised?   
822         Xylophone                      Can a xylophone be 3 octaves?   
823         Xylophone                 Can a short bar follow a long bar?   
824         Xylophone                     Did vibraphones exist in 1930?   

                                                Answer  \
0                                                  yes   
1                                                  yes   
2                                                   no   
3                                                   no   
4                                                  yes   
..                                                 ...   
820  Arnold Schlick's Spiegel der Orgelmacher und O...   
821          by a bright, sharp tone and high register   
822                                                yes   
823                                                 no   
824                                                yes   

    DifficultyFromQuestioner DifficultyFromAnswerer    ArticleFile  
0                       easy                   easy  data/set4/a10  
1                       easy                   easy  data/set4/a10  
2                       easy                   easy  data/set4/a10  
3                       easy                   easy  data/set4/a10  
4                       easy                 medium  data/set4/a10  
..                       ...                    ...            ...  
820                   medium                 medium   data/set2/a8  
821                   medium                 medium   data/set2/a8  
822                     hard                   hard   data/set2/a8  
823                     hard                   hard   data/set2/a8  
824                     hard                   hard   data/set2/a8  

[825 rows x 6 columns]

In [16]:
from collections import defaultdict

Articles = defaultdict(list)

# for i,path in enumerate(df['ArticleFile']):
#     if df['ArticleTitle'][i] not in list(Articles.keys()):
#         Articles[df['ArticleTitle'][i]] = Get_Tokens(path)

## Creating a Custom Dataset for our Articles

In [ ]:
def read_file(path):
    with open('../Data/Question_Answer_Dataset_v1.2/'+'S10/'+file_path+'.txt','r') as g:
        text = g.read()
    return Article

class CustomImageDataset(Dataset):
    def __init__(self, article_file_names,questions,answers):
        
#         Articles = defaultdict(list)
#         for i, path in enumerate(article_file_names):
#             if article_file_names[i] not in list(Articles.keys()):
#                 Articles[article_file_names[i]] = read_file()
        for i,Q in enumerate(questions):
            if answers[i] in ['Yes','No']:
                continue
            
                
                
        self.
        self.img_labels = pd.read_csv(annotations_file)
        self.img_dir = img_dir
        self.transform = transform
        self.target_transform = target_transform

    def __len__(self):
        return len(self.img_labels)

    def __getitem__(self, idx):
        img_path = os.path.join(self.img_dir, self.img_labels.iloc[idx, 0])
        image = read_image(img_path)
        label = self.img_labels.iloc[idx, 1]
        if self.transform:
            image = self.transform(image)
        if self.target_transform:
            label = self.target_transform(label)
        return image, label

In [4]:
x = [[1,2,3],[4,5,3]]

In [5]:
y = [[13,22,33],[34,35,23],[44,33,22]]

In [6]:
x.extend(y)

In [8]:
x.extend([[1,2,3],[5,43,4]])

In [9]:
x

[[1, 2, 3],
 [4, 5, 3],
 [13, 22, 33],
 [34, 35, 23],
 [44, 33, 22],
 [1, 2, 3],
 [5, 43, 4]]

In [10]:
x.count([1,2,3])

2

In [11]:
x.count([4,5,3])

1

In [12]:
feat_len = 7
PAD = np.ones(feat_len)*-1

In [13]:
PAD

array([-1., -1., -1., -1., -1., -1., -1.])

In [15]:
check = [PAD for i in range(4)]

In [16]:
check

[array([-1., -1., -1., -1., -1., -1., -1.]),
 array([-1., -1., -1., -1., -1., -1., -1.]),
 array([-1., -1., -1., -1., -1., -1., -1.]),
 array([-1., -1., -1., -1., -1., -1., -1.])]

In [17]:
max_len  = 25

ours = [np.array([1,1,1,1,1,1,1]) for i in range(20)]

In [19]:
padding_array = [PAD for i in range(max_len - len(ours))]

In [20]:
padding_array

[array([-1., -1., -1., -1., -1., -1., -1.]),
 array([-1., -1., -1., -1., -1., -1., -1.]),
 array([-1., -1., -1., -1., -1., -1., -1.]),
 array([-1., -1., -1., -1., -1., -1., -1.]),
 array([-1., -1., -1., -1., -1., -1., -1.])]

In [21]:
len(padding_array)

5

In [22]:
ours.extend(padding_array)

In [23]:
len(ours)

25

In [29]:
ours = np.array(ours)

In [25]:
from sklearn.model_selection import train_test_split

In [30]:
all = np.array([ours,ours,ours,ours])

In [33]:
out = np.zeros(25)
out[4]=1
out = np.array([out,out,out,out])
print(out.shape)

(4, 25)


In [31]:
all.shape

(4, 25, 7)

In [35]:
X_train, X_test, y_train, y_test = train_test_split(all, out, test_size=0.20, random_state=42)

In [37]:
X_train.shape

(3, 25, 7)